name: Publish TypeScript Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'typescript/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push tags and commit version updates
    environment: npm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        working-directory: typescript
        run: pnpm install

      - name: Run Tests
        working-directory: typescript
        run: |
          node --import=tsx --experimental-test-snapshots --test-concurrency=1 --test tests/*.test.ts

      - name: Apply Version Updates
        working-directory: typescript
        run: |
          # Force pnpm workspace recognition @ https://www.perplexity.ai/search/github-workflows-typescript-pu-2CcFkyNPSJ.fnCXbNF47RQ#0
          touch pnpm-workspace.yaml
          # Ensure package.json exists
          if [ ! -f "package.json" ]; then
            echo "Missing package.json file."
            exit 1
          fi
          pnpm dlx @changesets/cli version

      - name: Build Project
        working-directory: typescript
        run: pnpm build

      - name: Publish to npm
        working-directory: typescript
        run: pnpm publish --filter ./ --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update TS version and publish'
          file_pattern: 'typescript/package.json typescript/.changeset/*'
          # The action defaults to pushing to the branch that triggered the workflow (main)
          # It also uses the github-actions[bot] user by default

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
